### ISSUE TITLE
a friend of lora developers

### ISSUE THREAD

**Issue by yanzi418** [FranMarelli/easy_wakaama#1]
could you give the lora gateway user guide for me?and so interested in lora gateway.now i Encounter problems.thanks

**Comment by yanzi418** [comment]
my email is 975375246@qq.com

**Comment by FranMarelli** [comment]
Hello, I'm sorry but for the moment I haven't made any guide for lora gateway. Have you checked [LoRa network](https://github.com/Lora-net/) ?

**Comment by yanzi418** [comment]
yes，now i already solve the problem
